# Generated by Django 5.1.7 on 2025-04-07 12:18

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aTimeSlot',
            fields=[
                ('id', models.CharField(default=booking.models.generate_unique_id, max_length=100, primary_key=True, serialize=False)),
                ('slot', models.CharField(max_length=10)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('month', models.CharField(blank=True, max_length=2, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.TimeField()),
                ('booked_by', models.CharField(max_length=255)),
                ('floor', models.CharField(choices=[('1st', '1st Floor'), ('2nd', '2nd Floor'), ('8th', '8th Floor')], max_length=10)),
                ('date', models.DateField()),
                ('room', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['date', 'time_slot'],
            },
        ),
    ]
