# Generated by Django 5.1.7 on 2025-04-10 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Floor name (e.g., '1st Floor')", max_length=50)),
                ('slug', models.SlugField(help_text="URL-friendly version of the name (e.g., 'floor-1')", unique=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which the floor appears in the dropdown')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.floor'),
        ),
    ]
