# Generated by Django 5.1.7 on 2025-04-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_add_floor_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['order'], 'verbose_name': 'Floor', 'verbose_name_plural': 'Floors'},
        ),
        migrations.AddField(
            model_name='floor',
            name='number',
            field=models.IntegerField(default=0, help_text='Floor number (e.g., 1 for 1st floor)', unique=True),
        ),
    ]
