# Generated by Django 5.1.7 on 2025-04-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_floor_options_floor_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='number',
        ),
        migrations.AddField(
            model_name='floor',
            name='rooms',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='floor',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='floor',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
