# Generated by Django 4.1.6 on 2023-08-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0048_alter_event_prize3rd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubatee',
            name='startup_sector',
            field=models.CharField(choices=[('Edutech', 'EduTech'), ('FinTech', 'FinTech'), ('AI-ML', 'AI-ML'), ('Healthcare', 'Healthcare'), ('E-Commerce', 'E-Commerce'), ('AR-VR', 'AR-VR'), ('Finserv', 'Finserv'), ('Gaming', 'Gaming'), ('Robotics', 'Robotics'), ('Electric Vehicles', 'Electric Vehicles'), ('Renewable Energy', 'Renewable Energy'), ('SaaS', 'SaaS'), ('Hardware', 'Hardware'), ('Agri Tech', 'Agri Tech'), ('Clean Tech', 'Clean Tech'), ('Others', 'Others')], max_length=100),
        ),
    ]
