# Generated by Django 4.1.6 on 2023-08-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0050_event_orderno_programme_orderno_team_orderno'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeyear',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/programmeyear'),
        ),
    ]
