# Generated by Django 4.1.6 on 2023-08-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0051_programmeyear_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='programmeyear',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='programmeyear'),
        ),
    ]
