# Generated by Django 4.1.6 on 2023-08-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0052_about_alter_programmeyear_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aspect',
            field=models.CharField(blank=True, choices=[('Square', 'Square'), ('16: 9', '16: 9'), ('3:4', '3:4'), ('2:1', '2:1')], max_length=100, null=True),
        ),
    ]
