# Generated by Django 4.2.4 on 2023-08-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0053_image_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='aspect',
            field=models.CharField(blank=True, choices=[('16', '16:9'), ('3', '3:4'), ('2', '2:1')], max_length=100, null=True),
        ),
    ]
