# Generated by Django 4.1.6 on 2023-09-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0053_image_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='aspect',
            field=models.CharField(blank=True, choices=[('16', '16:9'), ('3', '3:4'), ('2', '2:1')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incubatee',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incubatee',
            name='company_website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incubatee',
            name='free_slots',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incubatee',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/incubatee/logo'),
        ),
        migrations.AlterField(
            model_name='incubatee',
            name='startup_scheme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incubatee',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='programmeyear',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/assets/programmeyear'),
        ),
        migrations.CreateModel(
            name='Iot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('devices', models.ManyToManyField(to='mainsite.iotdevice')),
            ],
        ),
    ]
