# Generated by Django 4.1.6 on 2023-09-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0054_banner_site_alter_features_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeyear',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
