# Generated by Django 4.2.4 on 2023-08-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0054_alter_image_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubatee',
            name='free_slots',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incubatee',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
