# Generated by Django 4.2.4 on 2023-09-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0055_banner_site_alter_incubatee_free_slots_and_more'),
        ('mainsite', '0055_banner_site_programmeyear_slug'),
    ]

    operations = [
    ]
