# Generated by Django 4.1.6 on 2023-10-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0056_merge_20230922_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotdevice',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/assets/iot'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='spec',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
