# Generated by Django 4.1.6 on 2023-10-07 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0057_rename_desc_iotdevice_description_banner_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmeyear',
            name='file',
        ),
        migrations.RemoveField(
            model_name='programmeyear',
            name='incubatees',
        ),
        migrations.RemoveField(
            model_name='programmeyear',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='programmeyear',
            name='slug',
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='spec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/assets/project')),
                ('file', models.FileField(blank=True, null=True, upload_to='static/assets/project')),
                ('website', models.CharField(blank=True, max_length=1000, null=True)),
                ('programmeyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.programmeyear')),
            ],
        ),
    ]
