# Generated by Django 4.1.6 on 2023-10-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0058_remove_programmeyear_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='people',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectDescription',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectLink',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectName',
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/assets/project'),
        ),
        migrations.AddField(
            model_name='project',
            name='programmeyear',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainsite.programmeyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
