# Generated by Django 5.1.7 on 2025-04-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0059_remove_project_people_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iot',
            options={'verbose_name': 'Equipment Types'},
        ),
        migrations.AlterModelOptions(
            name='iotdevice',
            options={'verbose_name': 'Equipment Device'},
        ),
        migrations.AddField(
            model_name='banner',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incubatee',
            name='founder_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/incubatee/founder_image'),
        ),
        migrations.AlterField(
            model_name='incubatee',
            name='startup_sector',
            field=models.CharField(choices=[('SaaS', 'SaaS'), ('Automobile', 'Automobile'), ('Agri Tech', 'Agri Tech'), ('Chemistry', 'Chemistry'), ('Construction', 'Construction'), ('Clean Tech', 'Clean Tech'), ('Aerospace', 'Aerospace'), ('Bio Tech', 'Bio Tech'), ('Defence', 'Defence'), ('Nano Tech', 'Nano Tech'), ('Food Tech', 'Food Tech'), ('Healthcare', 'Healthcare'), ('AR-VR', 'AR-VR'), ('ICT', 'ICT'), ('Manufacturing', 'Manufacturing'), ('Edu Tech', 'Edu Tech'), ('Energy', 'Energy'), ('Others', 'Others')], max_length=100),
        ),
    ]
