# Generated by Django 5.1.7 on 2025-04-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0060_alter_iot_options_alter_iotdevice_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='about',
        ),
    ]
